application: bitlyer
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/insert
  script: insert.php

- url: /$
  script: info.php

- url: /.*
  script: 404.php
